config/routes.rb
require 'sidekiq/web'
require 'sidekiq-status/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

Rails.application.routes.draw do
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, :at => '/'

  authenticate :spree_user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  scope module: :nelou do
    match '/globalsign', to: proc { [200, {}, ['125hxH ']] }, via: :get
    match '/404', to: 'errors#not_found', via: :all

    get '/designers', to: 'designer_labels#index', as: :nelou_designer_labels
    get '/designer/:id', to: 'designer_labels#show', as: :nelou_designer_label

    get '/designer_registration', to: 'designers#new', as: :new_designer
    post '/designer_registration', to: 'designers#create', as: :create_designer

    get '/help', to: 'pages#help', as: :help
    get '/imprint', to: 'pages#imprint', as: :imprint
    get '/privacy', to: 'pages#privacy', as: :privacy
    get '/terms-of-use', to: 'pages#terms_of_use', as: :terms_of_use

    post '/newsletter/unsubscribe', to: 'subscriptions#unsubscribe', as: :unsubscribe

    namespace :admin do
      get '/dashboard', to: 'dashboard#index', as: :dashboard
      get '/changelog', to: 'changelog#index', as: :changelog

      resources :designers, only: [ :index, :new, :create ], as: :nelou_designers
      resources :designer_labels, except: [ :show ], as: :nelou_designer_labels
      resources :wishlists, only: [ :index, :show ], as: :nelou_wishlists

      get '/orders_export', to: 'orders_export#index', as: :export_orders

      resources :size_option_types, except: [ :show ], as: :nelou_size_option_types do
        resources :size_option_values, only: [ :update ], as: :nelou_size_option_value
      end
      delete '/size_option_values/:id', to: 'size_option_values#destroy', as: :nelou_size_option_value
    end

    get '/admin/products/:product_id/sale', to: 'admin/sales#index', as: :admin_nelou_sales
    post '/admin/products/:product_id/sale', to: 'admin/sales#create'
    get '/admin/products/:product_id/sale/new', to: 'admin/sales#new', as: :new_admin_nelou_sale
    delete '/admin/products/:product_id/sale/cancel', to: 'admin/sales#cancel', as: :cancel_admin_nelou_sale
  end

  # Redirect for legacy routes
  get '/artikel-:id(/*ignored)', to: redirect('/products/%{id}?locale=de', status: 301), constraints: { id: /[0-9]+/ }
  get '/article-:id(/*ignored)', to: redirect('/products/%{id}?locale=en', status: 301), constraints: { id: /[0-9]+/ }
  get '/articulo-:id(/*ignored)', to: redirect('/products/%{id}?locale=en', status: 301), constraints: { id: /[0-9]+/ }

  get '/designerprofil/:slug', to: redirect('/designer/%{slug}?locale=de', status: 301), constraints: { id: /[0-9a-zA-Z\-]+/ }
  get '/label/:slug', to: redirect('/designer/%{slug}?locale=en', status: 301), constraints: { id: /[0-9a-zA-Z\-]+/ }
  get '/designerprofile/:slug', to: redirect('/designer/%{slug}?locale=en', status: 301), constraints: { id: /[0-9a-zA-Z\-]+/ }

  get '/de', to: redirect('/?locale=de', status: 301)
  get '/en', to: redirect('/?locale=en', status: 301)
end

Spree::Core::Engine.add_routes do
  get 'orders/:id/invoice' => 'orders#invoice', as: :order_invoice

  get '/new', to: 'taxons#recent', as: :recent_products
  get '/limit', to: 'taxons#limited', as: :limited_products
  get '/sale', to: 'taxons#on_sale', as: :sale_products
  get '/eco', to: 'taxons#eco', as: :eco_products

  get '/wished_products', to: 'wished_products#create'

  resources :products, :only => [:index, :show] do
    member do
      get 'images', defaults: {format: :json}
    end
  end
end

app/models/concerns/nelou/attachment_from_url.rb
module Nelou
  module AttachmentFromUrl
    extend ActiveSupport::Concern

    module ClassMethods
      def allow_from_url(*args)
        args.each do |attribute|
          define_method "#{attribute}_from_url" do |url|
            if check_url(url)
              send "#{attribute}=", URI.parse(url)
            else
              send "#{attribute}=", nil
            end
          end
        end
      end
    end

    private

    def check_url(url)
      uri = URI(url)
      request = Net::HTTP.new uri.host
      response = request.request_head uri.path
      response.code.to_i == 200
    end
  end
end

app/models/concerns/nelou/contains_designer.rb
module Nelou
  module ContainsDesigner
    extend ActiveSupport::Concern

    included do
      scope :containing_designer, -> (designer_label) { includes(:designer_labels).where("#{Nelou::DesignerLabel.quoted_table_name}.id": designer_label.id) }
    end

    def contains_products_from_designer(designer_label)
      designer_labels.map(&:id).include?(designer_label.id)
    end
  end
end

app/models/concerns/nelou/has_custom_file_name.rb
# Shamelessly stolen from
# @see https://gist.github.com/audionerd/4703b4ed3ddad82999f7

module Nelou
  module HasCustomFileName
    extend ActiveSupport::Concern

    def generate_hex_for_file_name(file_name)
      '%s%s' % [SecureRandom.hex(8), File.extname(file_name).downcase]
    end

    module ClassMethods
      def has_custom_file_name(attachment_name, callback)
        send(:"before_#{attachment_name}_post_process", :"set_#{attachment_name}_file_name")

        define_method :"set_#{attachment_name}_file_name" do |*_args|
          old_file_name = send(:"#{attachment_name}_file_name")
          new_file_name = send(callback, old_file_name)
          send(attachment_name).instance_write(:file_name, new_file_name)
        end
      end
    end
  end
end

app/models/concerns/nelou/legacy/login.rb
# @see https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address

module Nelou
  module Legacy
    module Login
      extend ActiveSupport::Concern

      included do
        devise :database_authenticatable, authentication_keys: [:login]
      end

      module ClassMethods
        def find_for_database_authentication(warden_conditions)
          conditions = warden_conditions.dup
          if login = conditions.delete(:login)
            where(conditions.to_h).where(['lower(legacy_username) = :value OR lower(email) = :value', { value: login.downcase }]).first
          elsif conditions.key?(:legacy_username) || conditions.key?(:email)
            where(conditions.to_h).first
          end
        end
      end

      def login=(login)
        @login = login
      end

      def login
        @login || legacy_username || email
      end
    end
  end
end

app/models/concerns/nelou/legacy/password.rb
# @see https://github.com/plataformatec/devise/wiki/How-To:-Migration-legacy-database

module Nelou
  module Legacy
    module Password
      extend ActiveSupport::Concern

      included do
        before_save :reset_legacy_password
      end

      def valid_password?(password)
        if legacy_password_hash.present?
          if ::Digest::MD5.hexdigest(password) == legacy_password_hash
            #self.password = password
            #self.legacy_password = nil
            #self.legacy_password_hash = nil
            #self.save!
            true
          else
            false
          end
        elsif legacy_password.present?
          if password == legacy_password
            #self.password = password
            #self.legacy_password = nil
            #self.legacy_password_hash = nil
            #self.save!
            true
          else
            false
          end
        else
          super(password)
        end
      end

      def reset_password(*args)
        self.legacy_password_hash = nil
        self.legacy_password = nil
        super(*args)
      end

      protected

      def reset_legacy_password
        if password.present?
          legacy_password_hash_will_change!
          legacy_password_will_change!

          self.legacy_password_hash = nil
          self.legacy_password = nil

          true
        end
      end

      def password_required?
        legacy_password_hash.present? || legacy_password.present? ? false : super
      end
    end
  end
end

app/models/concerns/nelou/price/sales.rb
module Nelou
  module Price
    module Sales
      extend ActiveSupport::Concern

      included do
        has_many :sale_prices, class_name: 'Nelou::SalePrice'
      end

      # TODO: also accept a class reference for calculator type instead of only a string
      def put_on_sale(value, calculator_type = 'Nelou::Calculator::AmountSalePriceCalculator', start_at = Time.now, end_at = nil, enabled = true)
        new_sale(value, calculator_type, start_at, end_at, enabled).save
      end
      alias create_sale put_on_sale

      def new_sale(value, calculator_type = 'Nelou::Calculator::AmountSalePriceCalculator', start_at = Time.now, end_at = nil, enabled = true)
        sale_price = sale_prices.new(value: value, start_at: start_at, end_at: end_at, enabled: enabled)
        sale_price.calculator_type = calculator_type
        sale_price
      end

      def active_sale
        on_sale? ? first_sale(sale_prices.active) : nil
      end
      alias current_sale active_sale

      def next_active_sale
        sale_prices.present? ? first_sale(sale_prices) : nil
      end
      alias next_current_sale next_active_sale

      def sale_price
        on_sale? ? active_sale.price : nil
      end

      def sale_price=(value)
        on_sale? ? active_sale.update_attribute(:value, value) : put_on_sale(value)
      end

      def discount_percent
        on_sale? ? (1 - (sale_price / original_price)) * 100 : 0.0
      end

      def original_price
        self[:amount]
      end

      def original_price=(value)
        self.price = value
      end

      def discount_percent
        on_sale? ? (1 - (sale_price / original_price)) * 100 : 0.0
      end

      def on_sale?
        sale_prices.active.present? && first_sale(sale_prices.active).value != original_price
      end

      def enable_sale
        return nil unless next_active_sale.present?
        next_active_sale.enable
      end

      def disable_sale
        return nil unless active_sale.present?
        active_sale.disable
      end

      def start_sale(end_time = nil)
        return nil unless next_active_sale.present?
        next_active_sale.start(end_time)
      end

      def stop_sale
        return nil unless active_sale.present?
        active_sale.stop
      end

      private

      def first_sale(scope)
        scope.order('created_at DESC').first
      end
    end
  end
end

app/models/concerns/nelou/product/limited_items.rb
module Nelou
  module Product
    module LimitedItems
      extend ActiveSupport::Concern

      included do
        before_save :set_sold_out
      end

      def limited?
        variants.where(limited: true).any?
      end

      def limited_items
        variants.map(&:limited_items).reject(&:nil?).sum
      end

      def limited_items_sold
        variants.map(&:limited_items_sold).reject(&:nil?).sum
      end

      def limited_items_available
        limited_items - limited_items_sold
      end

      def not_in_stock?
        !available? || (limited? && (limited_items_available <= 0))
      end

      def in_stock?
        !not_in_stock?
      end

      private

      def set_sold_out
        self.sold_out = not_in_stock?
        true
      end
    end
  end
end

app/models/concerns/nelou/product/option_filters.rb
module Nelou
  module Product
    module OptionFilters
      extend ActiveSupport::Concern

      included do
        scope :option_any, -> (opts) { joins(:variants_including_master => :option_values).where("#{Spree::OptionValue.quoted_table_name}.id": opts) }
        scope :option_all, -> (opts) { option_any(opts).group("#{Spree::Product.quoted_table_name}.id").having("COUNT(DISTINCT #{Spree::OptionValue.quoted_table_name}.id) = ?", opts.length) }
      end
    end
  end
end

app/models/concerns/nelou/product/sales.rb
module Nelou
  module Product
    module Sales
      extend ActiveSupport::Concern

      included do
        delegate_belongs_to :master, :active_sale_in, :current_sale_in, :next_active_sale_in, :next_current_sale_in,
                            :sale_price_in, :on_sale_in?, :on_sale?, :original_price_in, :discount_percent_in, :sale_price, :original_price
      end

      def put_on_sale(value, calculator_type = 'Nelou::Calculator::AmountSalePriceCalculator', all_variants = true, start_at = Time.now, end_at = nil, enabled = true)
        run_on_variants(all_variants) { |v| v.put_on_sale(value, calculator_type, true, start_at, end_at, enabled) }
      end
      alias create_sale put_on_sale

      def enable_sale(all_variants = true)
        run_on_variants(all_variants, &:enable_sale)
      end

      def disable_sale(all_variants = true)
        run_on_variants(all_variants, &:disable_sale)
      end

      def start_sale(end_time = nil, all_variants = true)
        run_on_variants(all_variants) { |v| v.start_sale(end_time) }
      end

      def stop_sale(all_variants = true)
        run_on_variants(all_variants, &:stop_sale)
      end

      def set_limited(all_variants = true)
        run_on_variants(all_variants, &:set_limited)
      end

      private

      def run_on_variants(all_variants)
        variants.each { |v| yield v } if all_variants && variants.present?
        yield master
      end
    end
  end
end

app/models/concerns/nelou/user/subscription.rb
module Nelou
  module User
    module Subscription

      extend ActiveSupport::Concern

      included do
        after_commit :subscribe, on: :create
        after_commit :unsubscribe, on: :destroy
      end

      def is_subscribed?
        # TODO: Figure out how to invalidate after subscribe
        Rails.cache.fetch("#{cache_key}/is_subscribed", expires_in: 1.minute) do
          Nelou::SubscriptionService.new.is_subscribed?(email)
        end
      end

      private

      def subscribe
        Nelou::Mailchimp::SubscribeUserJob.perform_later id
      end

      def unsubscribe
        Nelou::Mailchimp::UnsubscribeUserJob.perform_later id
      end

    end
  end
end

app/models/concerns/nelou/variant/limited_items.rb
module Nelou
  module Variant
    module LimitedItems
      extend ActiveSupport::Concern

      included do
        validates :limited_items, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
        validates :limited_items_sold, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
        validates :limited_items, presence: true, if: :limited?
        validates :limited_items_sold, numericality: { less_than_or_equal_to: :limited_items }, if: :limited?

        after_save :set_sold_out_on_product
      end

      def limited?
        limited
      end

      def limited_items_available
        if limited_items.nil? || (limited_items_sold || 0) > limited_items
          0
        else
          limited_items - (limited_items_sold || 0)
        end
      end

      def can_supply?
        !limited? || ((limited_items_sold || 0) <= limited_items)
      end

      def sold_out?
        not can_supply?
      end

      def set_limited
        self.limited = true
      end

      private

      def set_sold_out_on_product
        self.product.update_columns( sold_out: self.product.not_in_stock?, updated_at: Time.now )
      end
    end
  end
end

app/models/nelou.rb
module Nelou
  def self.table_name_prefix
    'nelou_'
  end
end

app/models/nelou/base_model.rb
module Nelou
  class BaseModel < ActiveRecord::Base

    # Has to be set explicitely, as rails does not detect namespace
    self.table_name_prefix = 'nelou_'

    self.abstract_class = true

  end
end

app/models/nelou/calculator/amount_sale_price_calculator.rb
module Nelou
  module Calculator
    class AmountSalePriceCalculator < Spree::Calculator
      # TODO: validate that the sale price is less than the original price
      def self.description
        'Calculates the sale price for a Variant by returning the provided fixed sale price'
      end

      def compute(sale_price)
        sale_price.value
      end
    end
  end
end

app/models/nelou/calculator/percent_off_sale_price_calculator.rb
module Nelou
  module Calculator
    class PercentOffSalePriceCalculator < Spree::Calculator

      def self.description
        "Calculates the sale price for a Variant by taking off a percentage of the original price"
      end

      def compute(sale_price)
        (1.0 - sale_price.value.to_f) * sale_price.variant.original_price.to_f
      end

    end
  end
end

app/models/nelou/exchange/rates.rb
module Nelou
  module Exchange
    class Rates
      def self.exchange_with(original, currency)
        update_rates!
        eu_bank.exchange_with(original, currency)
      end

      private

      def self.cache_path
        File.join(Rails.root, 'tmp', 'exchange_rates.xml')
      end

      def self.eu_bank
        @@eu_bank ||= EuCentralBank.new
      end

      def self.update_rates!
        if !eu_bank.rates_updated_at || eu_bank.rates_updated_at < Time.now - 1.days
          eu_bank.save_rates(cache_path)
          eu_bank.update_rates(cache_path)
        end
      end
    end
  end
end

app/views/nelou/designer_labels/index.html.erb
<% @body_id = 'designer-directory' %>

<div class="directory-listing designer-labels">

  <h1><%= t('.nelou_designers') %></h1>

  <div class="directory-options sort-options" role="navigation">
    <ul id="filters" class="sort-option-list">
      <li class="sort-option active" data-sortby="name"><%= t('.a_to_z') %></li>
      <li class="sort-option" data-sortby="country"><%= t('.country') %></li>
    </ul>
  </div>

  <%= cache([I18n.locale, @designer_labels.maximum(:updated_at)]) do %>

    <div id="directory" class="directory-sections filterable" role="main">

      <div class="directory-collection js-show-by-param name">

        <ul class="directory-navigation">
          <% all_letters = @designer_labels.map(&:first_letter).uniq %>
          <% ('A'..'Z').each do |l| %>
            <li>
              <% if all_letters.include?(l) %>
                <a href="#<%= l %>"><%= l %></a>
              <% else %>
                <span><%= l %></span>
              <% end %>
            </li>
          <% end %>
        </ul>

        <div class="directory-lists">
          <% partition_hash(@designer_labels.group_by(&:first_letter)).each do |column| %>
            <ul class="directory-list directory-entries-list designer-labels">
              <% column.each do |pair| %>
                <% letter = pair.first %>
                <% designer_labels = pair.second %>
                <% next if designer_labels.nil? %>
                <li class="directory-section">
                  <h3 class="directory-section-header letter" data-sort-option="<%= letter %>"><a name="<%= letter %>"><%= letter %></a></h3>
                  <ul class="section-entries">
                    <% designer_labels.sort_by { |d| d.name.try(&:parameterize) }.each do |designer_label| %>
                      <li class="section-entry" data-name="<%= designer_label.name %>" data-country="<%= designer_country_name(designer_label) %>">
                        <%= link_to nelou_designer_label_path(designer_label) do %>
                          <%= designer_label.name %>
                        <% end %>
                        <span class="location"><%= [designer_label.city, designer_country_name(designer_label)].reject(&:nil?).reject(&:blank?).join(', ') %></span>
                      </li>
                    <% end %>
                  </ul>
                </li>
              <% end %>
            </ul>
          <% end %>
        </div>

      </div>

      <div class="directory-collection js-show-by-param country" style="display: none;">

        <div class="directory-lists">
          <% partition_hash(@designer_labels.reorder(:country).group_by(&:country), 4, true).each do |column| %>
            <ul class="directory-list directory-entries-list designer-labels">
              <% column.each do |pair| %>
                <% country_code = pair.first %>
                <% country = get_country_name(country_code) %>
                <% designer_labels = pair.second %>
                <% next if designer_labels.nil? %>
                <li class="directory-section">
                  <h3 class="directory-section-header country" data-sort-option="<%= country_code %>"><a name="<%= country_code %>"><%= country %></a></h3>
                  <ul class="section-entries">
                    <% designer_labels.sort_by { |d| d.name.try(&:parameterize) }.each do |designer_label| %>
                      <li class="section-entry" data-name="<%= designer_label.name %>" data-country="<%= country %>">
                        <%= link_to nelou_designer_label_path(designer_label) do %>
                          <%= designer_label.name %>
                        <% end %>
                        <span class="location"><%= [designer_label.city, designer_country_name(designer_label)].reject(&:nil?).reject(&:blank?).join(', ') %></span>
                      </li>
                    <% end %>
                  </ul>
                </li>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>

    </div>

  <% end %>

</div>

app/views/nelou/designer_labels/show.html.erb
<div class="designer-label">
  <%= cache([@designer_label.id, I18n.locale, @designer_label.updated_at, @designer_label.products.maximum(:updated_at)]) do %>
    <div class="designer-label-top">
      <div class="designer-label-buttons">
        <button class="designer-label-button tab-button active" data-target='#designer-label-collection'>
          <%= t('.collection') %>
        </button>
        <% if @designer_label.has_products_on_sale? %>
          <button class="designer-label-button tab-button" data-target='#designer-label-on-sale'>
            <%= t('.sale') %>
          </button>
        <% end %>
        <button class="designer-label-button tab-button" data-target='#designer-label-about'>
          <%= t('.about') %>
        </button>
      </div>
      <div class="designer-label-logo">
        <%= image_tag @designer_label.logo(:profile), srcset: "#{@designer_label.logo(:profile_2x)} 2x" %>
      </div>
    </div>
    <div class="designer-label-page active" id="designer-label-collection">
      <div class="desinger-label-profile" style="background:<%= @designer_label.background_colour %>">
        <div class="designer-label-profile-left">
          <%= image_tag @designer_label.profile_image(:profile), srcset: "#{@designer_label.profile_image(:profile_2x)} 2x", alt: @designer_label.name %>
        </div>
        <div class="designer-label-profile-right">
          <div class="designer-label-profile-name">
            <%= @designer_label.name %>
          </div>
          <div class="designer-label-profile-text">
            <%= truncate scrub(@designer_label.short_description), length: 500, separator: ' ', omission: '' do %>
              <%= raw('&hellip;') %>
            <% end %>
          </div>
          <% if @designer_label.photo_credits.present? %>
            <div class="designer-label-profile-credits">
              <%= t('.photo_by', by: @designer_label.photo_credits) %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="designer-label-collection">
        <%= render partial: 'spree/shared/products', locals: { products: @designer_label.products.not_deleted.available.descend_by_available_on } %>
      </div>
    </div>
    <% if @designer_label.has_products_on_sale? %>
      <div class="designer-label-page" id="designer-label-on-sale">
        <div class="designer-label-collection">
          <%= render partial: 'spree/shared/products', locals: { products: @designer_label.products.not_deleted.available.on_sale.descend_by_available_on } %>
        </div>
      </div>
    <% end %>
    <div class="designer-label-page" id="designer-label-about">
      <div class="desinger-label-profile designer-label-about">
        <div class="designer-label-profile-left">
          <%= image_tag @designer_label.profile_image(:profile), srcset: "#{@designer_label.profile_image(:profile_2x)} 2x", alt: @designer_label.name %>
        </div>
        <div class="designer-label-profile-right">
          <div class="designer-label-profile-text">
            <% if @designer_label.profile.present? %>
              <%= longtext_to_html(@designer_label.profile) %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>